name: kanhas
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Paket Anda yang sudah ada
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  image_picker: ^1.2.1
  path_provider: ^2.1.5

  # Paket Splash Screen
  flutter_native_splash: ^2.4.0

  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Paket Launcher Icon
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

  # Daftarkan folder assets
  assets:
    - assets/images/

# --- 4. KONFIGURASI IKON ---
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  # --- PERBAIKAN: Ganti .jpg menjadi .png ---
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

# --- 5. KONFIGURASI SPLASH SCREEN ---
flutter_native_splash:
  color: "#FFFFFF"
  # --- PERBAIKAN: Ganti .jpg menjadi .png ---
  image: "assets/images/logo.png"
  android: true
  ios: true

  android_12:
    # --- PERBAIKAN: Ganti .jpg menjadi .png ---
    image: "assets/images/logo.png"
    color: "#FFFFFF"